apiVersion: v1
kind: Config
clusters:
  - clusters:
      certificate-authority: ca.crt
      server: https://kube0apiserver:6443
    name: kubernetes
users:
  - name: kubernetes-admin
    user:
      client-certificate: admin.crt
      client-key: admin.key
