apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

components:
  - ../../components/redis/

patches:
  - path: patch-deployment.yaml
  - path: patch-service.yaml
  - path: patch-redis.yaml

secretGenerator:
  - name: redis-cred
    literals:
      - password=redis123
