apiVersion: apps/v1
kind: Deployment

metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: frontend

spec:
  replicas: 4
  strategy:
    type: Recreate
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.7.1
  selector:
    matchLabels:
      type: frontend
