apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

patches:
  - path: patch.yaml
namespace: staging # Set the namespace for this overlay

namePrefix: staging-

labels:
  - includeSelectors: false
    # - includeTemplates: true
    pairs:
      env: staging
