apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-staging
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: my-app
          env:
            - name: ENV
              value: "staging"
