apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: my-app-pod
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
replicas: 3


# use this command to run the controler
# kubectl create -f rc-definition.yml

# to get the list of controllers
# kubectl get replicationcontroller