apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

# patches:
#   - path: patch.yaml
namespace: prod # Set the namespace for this overlay

namePrefix: prod-

labels:
  - includeSelectors: false
    pairs:
      env: prod

replicas:
  - name: my-app
    count: 5

images:
  - name: nginx
    newTag: 1.8.2
