apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-prod
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: my-app
          env:
            - name: ENV
              value: "production"
