resources:
  - nginx-deployment.yaml
  - nginx-service.yaml
# deploy
# kustomize build k8s | kubectl apply -f -
# or
# kubectl apply -k k8s/
# kustomize build k8s | kubectl delete -f -
# or
# kubectl delete -k k8s/
# kustomize build dev/
# kubectl apply -k /root/code/k8s/overlays/QA
# kubectl apply -k QA/
