apiVersion: v1
kind: Service
metadata:
  labels:
    company: MilanTech
  name: nginx-loadbalancer-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    company: MilanTech
    component: nginx
