apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    tier: data-processor
spec:
  containers:
    - name: data-processor
      image: data-processor
  affinity:
    requredDuringSchedulingIgnoredDruringExecution:
      nodeSelectorTerms:
        - key: size
          operator: In
          values:
            - Large
            - Medium

        # - key: size
        #   operator: NotIn
        #   values:
        #     - Small
