apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    tier: frontend
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 8080
  tolerations:
    - key: spray
      value: mortein
      effect: NoSchedule
