apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
profiles:

  - schedulerName: my-scheduler-2
    plugins:
      score:
        disabled:
          - name: TaintToleration
        enabled:
          - name: MyCutstomPluginA
          - name: MyCutstomPluginA

  - schedulerName: my-scheduler-3
      plugins:
      score:
        disabled:
          - name: '*'
        enabled:
          - name: '*'
          
  - schedulerName: my-scheduler-4
leaderElection:
  leaderElect: false
