apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
rules:
  - apiGroups: [""]
    resources: [""]
    verbs: ["get", "create", "update"]
    resourceNames: ["blue", "orange"]
