apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

components:
  - ../../components/postgres/

patches:
  - path: patch-deployment.yaml
  - path: patch-service.yaml
  - path: patch-postgres.yaml

secretGenerator:
  - name: postgres-cred
    literals:
      - password=postgres123
