apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  template:
    spec:
      containers:
        - name: postgres
          env:
            - name: POSTGRES_DB_ROOT_USERNAME
              value: mypostgres
            - name: POSTGRES_DB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-cred
                  key: password
