apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: nginx:latest
          ports:
            - containerPort: 80
      # containers:
      #   - name: mypostgresdb
      #     image: postgres:8
      #   - name: nginxapp
      #     image: nginx:1.7.9
      #   - name: myapp
      #     image: my-demo-app:latest
      #   - name: alpine-app
      #     image: alpine:3.7
