apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          # env:
          #   - name: POSTGRES_DB_ROOT_USERNAME
          #     valueFrom:
          #       configMapKeyRef:
          #         name: postgres-creds
          #         key: username
          #   - name: POSTGRES_DB_ROOT_PASSWORD
          #     valueFrom:
          #       configMapKeyRef:
          #         name: postgres-creds
          #         key: password
