# Let's fix that. Create a new PersistentVolumeClaim
# by the name of local-pvc that should bind to the volume local-pv.
# Inspect the pv local-pv for the specs.
# PVC: local-pvc
# Correct Access Mode?
# Correct StorageClass Used?
# PVC requests volume size = 500Mi?

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 500Mi


apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      volumeMounts:
        - name: local-pvc-volume
          mountPath: /var/www/html
  volumes:
    - name: local-pvc-volume
      persistentVolumeClaim:
        claimName: local-pvc



apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: delayed-volume-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

