apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  template:
    spec:
      containers:
        - name: postgres
          env:
            - name: POSTGRES_DB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-creds
                  key: username
            - name: POSTGRES_DB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-creds
                  key: password
