apiVersion: apiextensions.k8s.io/v1
kind: CustomeResourceDefinition
metadata:
  name: flighttickets.flights.com
spec:
  scope: Namespaced
  group: flighs.com
  names:
    kind: FlightTicket
    singular: flightticket
    plural: flighttickets
    shortNames:
      - ft
    version:
      - name: v1
        served: true
        storage: true
    shema:
      openAPIV3Shema:
        type: object
        properties:
          spec:
            type: object
            properties:
              from:
                type: string
              to:
                type: string
              number:
                type: string
