apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    name: webapp
spec:
  containers:
    - name: webapp
      image: kodekloud/webapp-color
      ports:
        - containerPort: 8080
      envFrom:
        - secretRef:
            name: app-secret
      resources:
        requests:
          memory: "2Gi"
          cpu: "2"
        limits:
          memory: "4Gi"
          cpu: "4"
      # volumes:
      #   - name: app-secret-volume
      #     secret:
      #       secretName: app-secret
