apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

patches:
  - path: patch.yaml
namespace: dev # Set the namespace for this overlay

namePrefix: dev-

labels:
  - includeSelectors: true
    pairs:
      env: dev
