apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: dev-my-app
          image: nginx:1.26.4
          env:
            - name: env
              value: "development"
