apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-dev
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: my-app
          env:
            - name: ENV
              value: "development"
