apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    tier: frontend
    app: myapp
spec:
  selector: 
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      name: apline
      labels:
        tier: frontend
        app: myapp
    spec:
      containers:
        - name: alpine-pod
          image: httpd:2.4-alpine